title: J. Campos-Obando
# logo: /assets/img/logo.png
description: I'm a computer science student. I'm interested in programming languages and compilers design .
show_downloads: false
google_analytics: UA-124636489-1 
theme: jekyll-theme-minimal
baseurl: ""
JEKYLL_GITHUB_TOKEN: 08543d51ddd6fceb3a075fc8a98de046605c1714

sass:
  style: compressed

permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

