title: J. Campos-Obando
# logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: false
#google_analytics: 
theme: jekyll-theme-minimal
baseurl: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
permalink: /:title

footer-links:
  github: barryclark/jekyll-now
  rss: /feed.xml

